// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/qx66/funnel/internal/biz"
	"github.com/qx66/funnel/internal/conf"
	"github.com/qx66/funnel/internal/sink"
	"github.com/segmentio/kafka-go"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initApp(bootstrap *conf.Bootstrap, arg *chan kafka.Message, logger *zap.Logger) (*app, error) {
	sinkKafka := sink.NewMQ(bootstrap, arg, logger)
	sinkRepo := sink.NewKafkaSink(sinkKafka)
	transfer := biz.NewTransfer(bootstrap, sinkRepo, arg, logger)
	mainApp := newApp(transfer)
	return mainApp, nil
}
